# Generated by Django 4.2.30 on 2026-05-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comments_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
