# Generated by Django 4.2.30 on 2026-05-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_comments_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_direction',
            field=models.BooleanField(default=False),
        ),
    ]
