# Generated by Django 4.2.30 on 2026-05-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_carbrand_carmodel_productcompatibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='direction',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
