# Generated by Django 4.2.30 on 2026-05-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='option_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='option_values',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcompatibility',
            name='years',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
