# Generated by Django 4.2.30 on 2026-05-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_option_title_product_option_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source_product_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='source_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
