# Generated by Django 4.2.30 on 2026-05-17 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_source_product_id_product_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_product_id', models.CharField(max_length=50)),
                ('source_comment_id', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('date_text', models.CharField(blank=True, max_length=50, null=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_imported', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='shop.productcomment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.product')),
            ],
            options={
                'unique_together': {('product', 'source_comment_id')},
            },
        ),
    ]
